services:
  server:
    image: megaexe-app:1.0
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
    container_name: megaexe
    depends_on:
      megaexedb:
        condition: service_healthy
  megaexedb:
    image: postgres
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=megaexedb
      - POSTGRES_USER=samscript
      - PGUSER=samscript
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "megaexedb"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
    driver: local
secrets:
  db-password:
    file: db/password.txt
